### ISSUE TITLE
Unfortunately, ANY_SOUND_2_BT has stopped.

### ISSUE THREAD

**Issue by unforgettableid** [kodered/AnySound2BT#1]
Hi!

I have a Samsung Galaxy S Relay.  This is a cellphone model a few years old.  It's probably similar to a Samsung Galaxy S3.

I downloaded and installed your app's .apk file from:

https://drive.google.com/file/d/0Byaspar4S5SESUNRaTBNV3BEbmc/view?usp=sharing

Then:
1.  I connect my Plantronics Explorer 243 headset to my phone.
2.  I open your app.
3.  I press the "Off" button in order to try to change it to "On".

The "Off" button turns blue for five seconds or so.  But it never changes to "On".

Then your app closes, and I see an error message:

`Unfortunately, ANY_SOUND_2_BT has stopped.`

I can reproduce this problem reliably.  It always happens.

Because I didn't get the app from the Google Play store, there's no "Report" button which lets me automatically send you more information.

P.S.  Thank you very much, anyway, for releasing this (and its source code) on GitHub.

P.P.S.  Later, I installed [Mono Bluetooth Router](https://play.google.com/store/apps/details?id=com.maxistar.monobluetoothfree) by Maxim Starikov, instead.  It works fine on my phone, and has never crashed.

**Comment by sauravpradhan** [comment]
This might be because of some Bluetooth API limitations in your platform. Can you please give me which OS are you running in so that I  can make the application compatible for your OS too. I tested in Nexus4 and OnePlus one running Kitkat 4.4 and Lollypop respectively and it seemed to work fine.

**Comment by unforgettableid** [comment]
Hi,

Thanks for your quick response.

I'm running Android 4.1.2.  With the usual Samsung modifications ("TouchWiz") included.

**Comment by sauravpradhan** [comment]
Have fixed from application point of view which I thought might have caused the issue. Updated permissions and mode. Please try the updated app and let me know if issues are there still. Please provide logs if possible. Please find the updated application from the new link in the readme.

**Comment by unforgettableid** [comment]
AnySound2BT now works on my phone, and doesn't crash. Thank you very much!

**Comment by sauravpradhan** [comment]
Thnkx a lot for verifying it ! Hope this app helps you and in future you have any concerns you can directly raise issue here! I don't have your handset so was curious to know it works or not !

**Comment by unforgettableid** [comment]
No problem.

Whenever you want to test an app in old versions of Android, you may download these old versions onto your PC.  Old versions of Android are downloadable for free using the "Android SDK Manager", from Google.  Then you can run them in the official Android emulator.

The ARM versions of Android run rather slowly on Intel CPUs.  The x86 versions may be faster.

**Comment by sauravpradhan** [comment]
I  am Android developer myself but since I basically code for builds greater than Kitkat 4.4.4 ! I basically don't download SDK's below 4.4 ! Anyways thanks for the suggestion !
