### ISSUE TITLE
Relicensing AnySound2BT

### ISSUE THREAD

**Issue by unforgettableid** [kodered/AnySound2BT#2]
Hi!

Some questions.
1. May anyone copy some (or all) of the AnySound2BT code into their own project?
2. May they even sell the resulting project as a paid app, without giving you any money?

**Comment by sauravpradhan** [comment]
It's just a part of my small Android experimentations ! :) ! Anybody can share / use or modify this code by just using a comment of me as the author !

**Comment by unforgettableid** [comment]
Even if they sell the code and make money from it?

**Comment by sauravpradhan** [comment]
At least I don't hope people use the code that way. It is just a very simple experimentation of my android learning.

**Comment by sauravpradhan** [comment]
Please check the application with the latest apk.

**Comment by unforgettableid** [comment]
OK. I'm starting to get a better idea of where you stand. Let me firm up my understanding even further.

Do you agree with the following?:
1. Anyone may modify and reuse the AnySound2BT code while writing open-source apps -- and even [sell the resulting software](http://www.gnu.org/philosophy/selling.en.html) -- as long as the resulting software will be open-source and freely-redistributable.
2. But nobody may reuse the AnySound2BT code as part of a closed-source proprietary commercial app.

What do you think? Sounds good?

**Comment by sauravpradhan** [comment]
yes of course ! :)

**Comment by unforgettableid** [comment]
Splendid!

Would you be willing to please relicense AnySound2BT as open-source, so that users may use and reuse it under the terms of "the GPL [version 2](https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-gpl-v2.0.md#how-to-apply-these-terms-to-your-new-programs) or later"?

**Comment by sauravpradhan** [comment]
Will do this soon ! :)

**Comment by unforgettableid** [comment]
Cool :)

Did you (and Eclipse) write _all_ of the code in AnySound2BT -- none of it is copied from the Internet or from any other app?

**Comment by sauravpradhan** [comment]
If you see the code yourself its just a simple mode changing code. Are you into serious something , coz so many questions regarding the plagiarism ?? :)

**Comment by sauravpradhan** [comment]
Hi I have updated the license in the readme of this project. Have a look.

**Comment by unforgettableid** [comment]
Regarding your message of July 16:

I haven't actually read all the AnySound2BT code.  :)  I was asking questions so that maybe it can eventually get into the F-Droid repositories.

Regarding the new license:

I took a look, and I'm happy with what I saw.  Thank you very much for applying a proper open-source license to your code!

**Comment by sauravpradhan** [comment]
I guess we can close this issue as fixed.
