### ISSUE TITLE
App version numbering

### ISSUE THREAD

**Issue by unforgettableid** [kodered/AnySound2BT#3]
Hi again!

When I go to **Settings** > **Application manager** > **AnySound2BT**, Android tells me that I am running Version 1.0 of your app.

But this can't be right. It's not the first version you've released; it's the second.

May I suggest you bump your app's version number to "1.1" or something like that?

**Comment by sauravpradhan** [comment]
Sure did not consider all these because it is just a sample app ! Will update it soon!

**Comment by sauravpradhan** [comment]
Please check the application with the latest apk.

**Comment by unforgettableid** [comment]
Today, I downloaded and installed the latest version of your app. I returned to **Settings > Application manager > AnySound2BT**, and it indeed reports "Version 1.1" now. Thank you for implementing this request!
