### ISSUE TITLE
Please make the main screen less spartan

### ISSUE THREAD

**Issue by unforgettableid** [kodered/AnySound2BT#4]
Hi!
AnySound2BT's main screen is rather spartan.  It contains nothing but an On/Off button.

It would be most splendid if you could please add some text to the screen.

Perhaps this?

---

AnySound2BT

Version 1.1

By: Saurav Pradhan &lt;sauravpradhan@example.com&gt;

This free utility lets you play music (and other audio) through any Bluetooth headset, even if the headset was designed to support phone calls only.

Your feedback is kindly requested. Please visit:
http://github.com/sauravpradhan/AnySound2BT/issues

The button below controls AnySound2BT. The button also always displays the utility's current status.

AnySound2BT is currently:

---

**Comment by sauravpradhan** [comment]
Thanks will consider your suggestion in the next version !

**Comment by sauravpradhan** [comment]
Please check the application with the latest apk.

**Comment by unforgettableid** [comment]
I tried the 1.1 .apk file today. It's better now. Thank you!
