### ISSUE TITLE
Suggested new icon

### ISSUE THREAD

**Issue by unforgettableid** [kodered/AnySound2BT#5]
Hi,

May I suggest you choose a nice new launcher icon for AnySound2BT?  I suggest:

https://upload.wikimedia.org/wikipedia/commons/7/73/P_treble_clef.svg

It was designed by Wikimedia Commons user "Booyabazooka", who said that s/he owns the copyright and releases the icon into the public domain.

**Comment by unforgettableid** [comment]
It was made by someone who is quite good at creating art.

**Comment by sauravpradhan** [comment]
How about some BT sign in that logo. If there's any other suggestion let me know. Something which depicts this app is related to BT or you can fork my repo and build your own with the icon you have given.

**Comment by unforgettableid** [comment]
I agree that it would be good to have a Bluetooth logo in the icon.  It would make it more obvious to users what AnySound2BT is for.

But, http://www.bluetooth.com/Pages/Trademarks.aspx says:

> The Bluetooth word mark, figure mark, combination mark, and Bluetooth Smart and Bluetooth Smart Ready marks are all trademarks that are owned by the Bluetooth SIG and licensed out for use to companies that are incorporating Bluetooth wireless technology into their products. To become a licensee, a company must become a member of the Bluetooth SIG.

So it sounds like I might have to pay money for a Bluetooth SIG membership if I want to add the Bluetooth logo into the "P_treble_clef.svg" icon.

I don't want to spend money for this, so I haven't added the logo into the icon.  :)

**Comment by sauravpradhan** [comment]
No worries I ll fix the icon issues !
